apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: spring-cronjob-currency-deployment
  labels:
    app: spring-cronjob-currency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cronjob-currency
  template:
    metadata:
      labels:
        app: spring-cronjob-currency
    spec:
      containers:
      - name: spring-cronjob-currency
        image: 'rawsanj/spring-cronjob-currency:0.1.8'
        resources:
          limits:
            memory: "1024Mi"
            cpu: "0.5"
          requests:
            memory: "1024Mi"
            cpu: "0.5"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: spring-cronjob-currency-config
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcp-stackdriver-key
            