apiVersion: v1
kind: Service
metadata:
  name: spring-cronjob-currency-service
spec:
  selector:
    app: spring-cronjob-currency
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
